### ISSUE TITLE
jquery-ui-themes taking up 20.1MB

### ISSUE THREAD

**Issue by nathany** [fatdude/jquery-ui-themes-rails#7]
Just seeing what gems are making our deployment larger.

It looks like the cache and log folders in the dummy app are pretty big. I'm not sure if those are shipping with the gem, but looking at the .gemspec, I'm guessing that could be the case.

**Comment by dgilperez** [comment]
I think this is fixed in https://github.com/fatdude/jquery-ui-themes-rails/pull/13
